# Generated by Django 5.1.1 on 2024-10-21 08:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_app', '0002_auto_20241011_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handhole',
            fields=[
                ('structure_id', models.UUIDField(primary_key=True, serialize=False)),
                ('structure_name', models.CharField(max_length=100)),
                ('sub_area_id', models.CharField()),
                ('street_id', models.CharField()),
                ('physical_address', models.CharField(max_length=255)),
                ('structure_placement', models.CharField(max_length=100)),
                ('handhole_material', models.CharField(max_length=100)),
                ('handhole_dimension', models.CharField(max_length=100)),
                ('handhole_wall_thickness', models.FloatField(max_length=100)),
                ('handhole_cover_type', models.CharField(max_length=100)),
                ('handhole_cover_shape', models.CharField(max_length=100)),
                ('handhole_cover_thickness', models.CharField(max_length=100)),
                ('cover_seal_type', models.CharField(max_length=100)),
                ('deployment_status', models.CharField(max_length=50)),
                ('design_approval', models.CharField(default=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cabinet_area', models.CharField(max_length=100)),
                ('project_id', models.CharField()),
                ('createdby', models.CharField(max_length=100)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('editedby', models.CharField(blank=True, max_length=100, null=True)),
                ('editedat', models.DateTimeField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'handhole',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PointFeature',
        ),
    ]
